### ISSUE TITLE
help plis?? :c

### ISSUE THREAD

**Issue by Maenso** [CoderCow/HouseRegions-Plugin#15]
[10/23/15 19:57:06] [Server API] Warning: Plugin "House Regions" has had an unhandled exception thrown by one of its NetGetData handlers: 
System.MissingFieldException: Field not found: 'Terraria.Main.tile'.
   in Terraria.Plugins.Common.Hooks.GetDataHookHandler.NetHooks_GetData(GetDataEventArgs e)
   in TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

**Comment by CoderCow** [comment]
Please use one of the current TShock / TSAPI builds.

**Comment by Maenso** [comment]
I'm currently using tshock 4.3.9 :/
