### ISSUE TITLE
Ownership Transfer

### ISSUE THREAD

**Issue by bippity** [CoderCow/HouseRegions-Plugin#17]
I was wondering if it's possible to implement a way to let a user transfer ownership to another player. It would be very useful for servers that "rent out" predefined houses to players. If this was added in, we could easily check if the player has already reached the house limit. 
I'm thinking the feature would probably work by removing the HouseRegion from the original owner, storing the region temporarily in memory, and then set it as a new HouseRegion for the new owner.

**Comment by CoderCow** [comment]
Shouldn't be hard to implement. I'll look into it when I have time.
