### ISSUE TITLE
/setowner not working correctly? - User is already an owner

### ISSUE THREAD

**Issue by bippity** [CoderCow/HouseRegions-Plugin#18]
I believe I'm testing this with default configurations (Deleted all regions and HouseRegion config files). 
After defining a house, upon trying to execute '/house setowner newPlayer', I'm given an error saying that the "player is already the owner of this region".
Anything that I might be doing wrong?

**Comment by CoderCow** [comment]
I should invest more time in testing things. Will be fixed in a few.

**Comment by bippity** [comment]
:heart:
