### ISSUE TITLE
Building the plugin

### ISSUE THREAD

**Issue by Jewsus** [CoderCow/HouseRegions-Plugin#19]
Hey I am not that great at coding and I get this error when building just wondering if there is something I am missing?

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\Jewsus\Desktop\TShock-Minitaka\SourceCode - OTAPI\CoderCow\HouseRegions-Plugin\packages\Mono.pdb2mdb.0.1.0.20130128\tools\pdb2mdb.exe" "C:\Users\Jewsus\Desktop\TShock-Minitaka\SourceCode - OTAPI\CoderCow\HouseRegions-Plugin\bin\Release\House Regions.dll"" exited with code 3.	House Regions			

I would guess I am missing something required like mono?

**Comment by CoderCow** [comment]
Sorry, looks like I forgot adding a packages.config to this project.
You get this error because you're missing the Mono.pdb2mdb nuget package which is required to build the mono debug symbols.

**Comment by vosdbk** [comment]
if u use vs2015 or higher, u need to download another pdb2mdb.exe
NuGet's packages is NOT useful.

**Comment by CoderCow** [comment]
I guess this has been resolved, so let me close this now.
