### ISSUE TITLE
the number of houses count problem, and about translate

### ISSUE THREAD

**Issue by vosdbk** [CoderCow/HouseRegions-Plugin#20]
HousingManager.cs
Line 75, should be `if (houseIndex == (maxHouses + 1))`

Btw, can i translate your mod to chinese?
I will NOT modify your anthor info, just add my name after you as "Translater xxx"

**Comment by CoderCow** [comment]
Thanks for the hint. 
No need to ask for permission. The license already permits you to fork this repository and to make any changes you like in the codebase (while keeping copyright notices tho).
