### ISSUE TITLE
House Define does not work

### ISSUE THREAD

**Issue by Aro2220** [CoderCow/HouseRegions-Plugin#9]
When a user uses /house define they can create the points with a wrench/wire but when they click inside the defined region, nothing happens. When they type /house it says they have 0/1 region defined and when they try to define a region again or delete the region they just made it says that they already have 1/1 regions defined and that the region doesn't even exist....

So now we can't remove the regions and nothing is actually protected.

**Comment by CoderCow** [comment]
I'll just guess this issue is outdated.
